language: dart
dart:
  - 1.24.3
  - stable
before_install:
  - ./pub2get.sh
script:
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run test
  - pub run dart_dev dart1-only -- coverage --no-html && bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
