name: r_tree
version: 1.1.0
description: R-tree implementation to index and query two-dimensional data
author: Taylor Anderson <taylor.anderson@workiva.com>
homepage: https://github.com/Workiva/r_tree

environment:
  sdk: '>=2.9.0 <3.0.0'

dev_dependencies:
  benchmark_harness: any
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.12.0
  dart_dev: ^3.0.0
  dart_dev_workiva:
    hosted:
      url: https://pub.workiva.org
      name: dart_dev_workiva
    version: ^1.0.0
  dart_style: ^1.3.1
  test: ^1.9.1
