name: r_tree
version: 1.0.2
description: 'A recursive RTree library written in Dart.'
authors:
  - Taylor Anderson <taylor.anderson@workiva.com>
homepage: https://github.com/Workiva/r_tree

environment:
  sdk: ">=1.24.2 <2.0.0"

dev_dependencies:
  benchmark_harness: any
  coverage: ^0.7.9
  dart_style: 1.0.7
  dart_dev: ^1.7.6
  test: ^0.12.0