name: Dart CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ 2.19.2 ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Check formatting
        run: dart format -l 120 --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == '2.18.7' }}
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
      - name: Publish SBOM to Release Assets
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
